### ISSUE TITLE
[Improve] fix mongo indexing and update operation.

### ISSUE THREAD

**Issue by rajatkb** [rajatkb/Conference-Notify#10]
The current implementation indexes on url (unique) and deadline (sorting). But since multiple scrappers will be writing using the same interface how can we ensure only the latest updates of particular conference is put in the db (overwriting allowed). But overwriting is not possible with unique index and upsert:True argument. The implementation needs changing given that we avoid bringing in data to the application side for any sort of verification.

**Comment by vipuldcoder** [comment]
I am interested with the issue.
