### ISSUE TITLE
[Feat.] insert to mongo db on having greater datestamp for deadline, trigger a rest call for same

### ISSUE THREAD

**Issue by rajatkb** [rajatkb/Conference-Notify#15]
The Database class currently does not checks for the deadline constraint. It may update the deadline of an mongo document from any of the scrapper plugin , and may lead to inconsistent or old date. Insertion should be avoided in such cases.

**REQUIREMENT**
* Figure out a a way to do the deadline date check.
* Achieve this without doing a (search -> bring data to application memory -> insert)
* Doing the above will only lead to more latency ( if used locks to preserve critical section ) for single insertion. Bringing in problems such as inconsistent writes when the scrappers are made parallel.

**Comment by vipuldcoder** [comment]
I am interested to work with the issue.

**Comment by abhishekgupta368** [comment]
I will do it?

**Comment by rajatkb** [comment]
Assigning it to @abhishekgupta368
