### ISSUE TITLE
[Feat.] landing page design for user application

### ISSUE THREAD

**Issue by rajatkb** [rajatkb/Conference-Notify#16]
**REQUIREMENT**
1. Landing page consisting of  search barc / categories
2. Some way to navigate to some list of Conference (may be clicking on search bar should open a top conference list with search bar on top)

**Comment by dwvicy** [comment]
I'd like to work on this issue!

**Comment by TheDudeThatCode** [comment]
@rajatkb  can you assign this to me as you know I am working on it.

**Comment by rajatkb** [comment]
Assigning to @TheDudeThatCode  as discussed over slack, @dwvicy slack me, so that we can work on helping you to pick some other issue.

**Comment by rajatkb** [comment]
@TheDudeThatCode  Revert back on the same ASAP.
