### ISSUE TITLE
[Feat.] landing page implementation

### ISSUE THREAD

**Issue by rajatkb** [rajatkb/Conference-Notify#17]
#16 Suggests a certain design mockup. 
The mockup needs to be put into an angular application.

**Comment by JanhaviDadhania** [comment]
Hello sir. I am Janhavi GSSoC participant. If I understand the issue correctly then it is implementation of mockup. I would like to take this up once the basic design is ready.

**Comment by rajatkb** [comment]
@JanhaviDadhania  Can you ping me on slack so that we can discuss this.
