### ISSUE TITLE
[Feat.] add new Scrapper for Guide2Reasearch

### ISSUE THREAD

**Issue by rajatkb** [rajatkb/Conference-Notify#2]
The current scrapper is collecting the information from wikicfp. One more such large aggregator of information is [Guide2Research](http://www.guide2research.com/). They also provide journal impact factor and other information relevant to researchers. Follow the guidelines in the Scrapper-Service to add your own service.

**Comment by vipuldcoder** [comment]
I am interested with the issue.

**Comment by Angelvicks** [comment]
Hello, please I am interested in this issue

**Comment by crazykoala666** [comment]
Really interested in it.

**Comment by siddhishree** [comment]
Interested in working on this. @rajatkb

**Comment by manasakalaga** [comment]
interested in working on this.

**Comment by rajatkb** [comment]
Assigning to @manasakalaga

**Comment by rajatkb** [comment]
@siddhishree  @crazykoala666  @Angelvicks  , if you guys are still interested in writing a scraper. Then you can suggest another website from where data can be collected. Also contact me over slack for the same. We can then create issues and assign to you guys.
