### ISSUE TITLE
[Docs] improve the Contributing.md with information about how to do PRs 

### ISSUE THREAD

**Issue by rajatkb** [rajatkb/Conference-Notify#20]
Many new beginners are facing trouble regarding git PRs. It would be great to have a section for the same in the Contributing.md.

**Comment by Kajol-Kumari** [comment]
I would like to work on this.

**Comment by rajatkb** [comment]
Assigning to @Kajol-Kumari

**Comment by rajatkb** [comment]
@Kajol-Kumari  updates merged
