### ISSUE TITLE
[Feat.] add getConference() query to  Conference model in Notifier-Service

### ISSUE THREAD

**Issue by rajatkb** [rajatkb/Conference-Notify#34]
Currently, there is only one `getOne` dummy async function for retrieving one document. The controller for the Conference model will be requiring few queries which will be contained by the Conference model class.  

*REQUIREMENT*  
-> add the required methods by following the controller requirements

*Where to look at*
-> controllers/conference.ts
-> models/conference.ts

**Comment by rajatkb** [comment]
@Kajol-Kumari  I am assigning it to you, leave a response for the same.

**Comment by Kajol-Kumari** [comment]
okay @rajatkb
