### ISSUE TITLE
[Improv.] improve schema for current mongodb storage , especially for category indexing

### ISSUE THREAD

**Issue by rajatkb** [rajatkb/Conference-Notify#36]
The category field in the current schema is storing an array of values.

`
"categories" : [
                "semantic web",
                "wireless",
                "web services",
                "internet"
        ],
`  

This cannot be indexed as these are not unique across each entry in the database. We have some queries that specifically require to get entries corresponding to one category. Like

query: get all conference of category "wireless"   

For such query, the complexity will rise to O(n) for the database. We need a solution to this problem.

**Comment by rajatkb** [comment]
Update: The array fields can be indexed through multi indexing. 

[Multikey indexing](https://docs.mongodb.com/manual/indexes/)
[Bounds of multi key indexing](https://docs.mongodb.com/manual/core/index-multikey/)
[ Bounds || ](https://docs.mongodb.com/manual/core/multikey-index-bounds/)

The documents can be indexed on the array fields for now. especially is the search criteria is only one entry from the array. Which allows for faster results (fist entry is used for index based filtering) . Currently we can resort to some sort of in memory caching to reduce response times and DB calls.

**Comment by Rukmini-Meda** [comment]
@rajatkb I would like to work on this issue. Please assign this to me as part of GSSoC'20.

**Comment by rajatkb** [comment]
The issue is resolved for now. But if you see any improvements can be done in the queries and indexed fields. You can put a PR.
