### ISSUE TITLE
[Feat.] implement routines for Conference service in Notifier-service application

### ISSUE THREAD

**Issue by rajatkb** [rajatkb/Conference-Notify#37]
This issue is dependent on #34  , #45 #46   , so if someone intends to address this will have to pick and address that issue first. The issue is also linked with #36 , given it will impact the performance of the response.   

*REQUIREMENTS*
-> complete implementation of  conference.ts 

*Where to look*  
-> src/services/conference.ts

PS: In order to implement them just follow the comments given

**Comment by rajatkb** [comment]
@Kajol-Kumari  assigning to you. Since you are engaged on this now.

**Comment by divyaprakash-Rx** [comment]
I want to work on this issue. Please assign it to me.

**Comment by rajatkb** [comment]
@divyaprakash-Rx  assigned , have a PR ready by tomorrow . It can be a draft PR to show some initial progress.

**Comment by divyaprakash-Rx** [comment]
OK
