### ISSUE TITLE
[Feat.] Adding Continous Integration (CI) Tool

### ISSUE THREAD

**Issue by sagar-sehgal** [rajatkb/Conference-Notify#39]
Since we are following Test Driven Development and some tests have already been added, it would be nice to integrate a Continous Integration tool like Travis CI or Github Actions. 

This will help in checking whether a new PR will break the original code or not by running the project and running the tests of the application.

**Comment by rajatkb** [comment]
Ohh I was working on this today. I thought since it will be required to have travis CI access to the repo which only I and the mentors had. Still if someone wants to tackle the same and make necessary commits + instruction + travils.yml files is welcome. 😃😄

**Comment by illseption** [comment]
Hi, I've recently worked on Travis integration and would like to take this up but I might need some guidance

**Comment by rajatkb** [comment]
@illseption  Ya sure , I am assigning this to you. Do get in touch with @sagar-sehgal  or me over slack for the same.

**Comment by illseption** [comment]
Hi, I've opened a PR #47. Please review when convenient, thanks!
