### ISSUE TITLE
[Base] design suggestion for [Angular] front end application 

### ISSUE THREAD

**Issue by rajatkb** [rajatkb/Conference-Notify#4]
Start the angular front end application project base. Start with creating new folder in the root/Application . Submit the PR request with your own branch commit as suggested in the contributing.md.

**REQUIREMENT**
* Create a basic clean UI (Material compliant would be a plus)
* Top: Search bar (Test with free rest endpoints)
* Card view for all conferences
* Single page event view for selection recurring reminder. We are trying to avoid user registration and rather have the application register itself to the backend so that the backend can serve the notification.

**Comment by vipuldcoder** [comment]
I am interested with the issue.

**Comment by vipuldcoder** [comment]
I am interested with the issue.

**Comment by Kajol-Kumari** [comment]
@rajatkb , If no one is working on this issue, i would like to go with this one.

**Comment by rajatkb** [comment]
@Kajol-Kumari  @vipuldcoder  and Shubhamdeep are to discuss on this and Shubhamdeep will be having a meet with me regarding the frontend design. So I think if we can discuss and break the task then three of you can tackle this. For now let me just have it assigned to the three of you. I will have a sepparate issue for the subtask.

**Comment by rajatkb** [comment]
Assigning to @Kajol-Kumari  and @vipuldcoder

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari @vipuldcoder and Shubhamdeep are to discuss on this and Shubhamdeep will be having a meet with me regarding the frontend design. So I think if we can discuss and break the task then three of you can tackle this. For now let me just have it assigned to the three of you. I will have a sepparate issue for the subtask.

okay @rajatkb In the mean time i will be making a basic angular structure using cli and will then add the requirements mentioned in the issue one by one.
