### ISSUE TITLE
[Improv.] introduce Jest test framework for unit test in Notifier-Service

### ISSUE THREAD

**Issue by rajatkb** [rajatkb/Conference-Notify#42]
Currently, the Notifier service has the base routes, controller and respective services ready. What we need now is a unit test framework that will test the route + the services response. With good predictable test cases to catch bugs early. For this we need to have the unit test framework setup for the project.

*REQUIREMENT*
* setup jest and package.json test commands properly
* write basic unit test for now to run.

**Comment by maheshschand** [comment]
Interested. I like to work on this issue. Could you please assign this issue @rajatkb ?

**Comment by rajatkb** [comment]
@maheshschand  , contact me over Slack. Assigning it to you.

**Comment by rajatkb** [comment]
@maheshschand Please rever back to me over slack. I am assgning a *deadline* of 19 March, considering the issue. It will be needed on immediate node.

**Comment by rajatkb** [comment]
@maheshschand  you can skip over the test for now. include the jest framework. and we will look into the test later. for just include the jest framework write a dummy test. Submit PR.
