### ISSUE TITLE
[Feat.] add getConferenceFromCategory() query to Conference model in Notifier-Service

### ISSUE THREAD

**Issue by rajatkb** [rajatkb/Conference-Notify#45]
Similar tp #34  , but with extra parameter of conference category provided.

*REQUIREMENTS*
- Write the function for getConferenceFromCategry() ,

*Where to look*
* models/conference.ts

**Comment by divyaprakash-Rx** [comment]
@rajatkb I want to work on this issue.
Please assign it to me.

**Comment by rajatkb** [comment]
Ok Assigning it to you. Contact Kajol over slack she is working on the other function, that is similar to this. Collaborate on this.

**Comment by divyaprakash-Rx** [comment]
@rajatkb Ok. Please assign.
