### ISSUE TITLE
[Feat.] add getCategories() query to Conference model in Notifier-Service

### ISSUE THREAD

**Issue by rajatkb** [rajatkb/Conference-Notify#46]
Write the routine for querying the database of all the unique conference categories it contains. Please do run the Scrapper service to collect the data , and take a look at the kind of data you will be dealing with.

*Where to look*
* src/models/conference.ts

**Comment by divyaprakash-Rx** [comment]
@rajatkb I want to work on this issue.
Please assign it to me.

**Comment by rajatkb** [comment]
Collaborate with Kajol , contact with her over slack. She is working on one of the functions in this file.

**Comment by rajatkb** [comment]
The other issue #45 is already assigned, you can collaborate with Kajol for the issue. The issues are on related terms.

**Comment by divyaprakash-Rx** [comment]
OK
