### ISSUE TITLE
[Improve] Remove pkg-resources from requirements.txt

### ISSUE THREAD

**Issue by sagar-sehgal** [rajatkb/Conference-Notify#48]
We need to remove `pkg-resources==0.0.0` from `requirements.txt` file [here](https://github.com/rajatkb/Conference-Notify/blob/9888d5b6a92bb001a8ba13de564622e854e0b391/Scrapper-Service/requirements.txt#L7).

When I tried to install the dependencies, I came across the following error. 
```
ERROR: Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from -r requirements.txt (line 7)) (from versions: none)
ERROR: No matching distribution found for pkg-resources==0.0.0 (from -r requirements.txt (line 7))
```

**Comment by Aman-Codes** [comment]
I am a GSSOC 2020 participant and I would like to work on this issue. Please assign me this issue @sagar-sehgal

**Comment by sagar-sehgal** [comment]
@Aman-Codes assigned

**Comment by sagar-sehgal** [comment]
@Aman-Codes Since this is a small issue, I request you to please update it fast. Maybe by tomorrow. When can I expect this from you?

**Comment by Aman-Codes** [comment]
@sagar-sehgal  Done Sir
