### ISSUE TITLE
Add ISSUE_TEMPLATE

### ISSUE THREAD

**Issue by Aman-Codes** [rajatkb/Conference-Notify#54]
@rajatkb @sagar-sehgal I am a GSSOC participant and I would like to add an issue template folder with pull request template and a new issue template.
![updated pull request](https://user-images.githubusercontent.com/54680709/77184265-935b7e00-6af5-11ea-8177-376f9f15bac7.PNG)

**Comment by rajatkb** [comment]
This format looks great. Awaiting on Sagar's confirmation.
