### ISSUE TITLE
[Bug] categories in conference collection is getting duplicated over multiple runs.

### ISSUE THREAD

**Issue by rajatkb** [rajatkb/Conference-Notify#64]
**Describe the bug**
The categories field is getting populated with the same data repeatedly over multiple runs, in the conference collection.

**To Reproduce**
1. Run the Scrapper-Service using  `python app.py -l debug -ls console  --test True`
2.. Close it using Ctrl-C and run it again.
2. Check conference categories data, you will see the conference data being repeated

**Expected behaviour**
There should be unique entries in the conference categories field.

**Additional context**
The bug is associated with insertion logic, need fix in that ASAP.

**Comment by vipul-aggarwal-099** [comment]
I am interested with the issue.
