### ISSUE TITLE
Add CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by Aman-Codes** [rajatkb/Conference-Notify#67]
**Is your feature request related to a problem? Please describe.**
No CODE_OF_CONDUCT.md file is present.

**Describe the solution you'd like**
@rajatkb   As a GSSOC participant I would like to add a CODE_OF_CONDUCT.md file in this project. Using [this]( https://www.contributor-covenant.org/version/1/4/code-of-conduct.html) as a reference. 

**Additional context**
### Screenshots

![code of conduct1](https://user-images.githubusercontent.com/54680709/77505634-beddc000-6e89-11ea-9dd5-f1e13ef6c6c9.PNG)
![code of conduct2](https://user-images.githubusercontent.com/54680709/77505638-c0a78380-6e89-11ea-8aa4-efcb21133da7.PNG)

**Comment by rajatkb** [comment]
@sagar-sehgal  Please review this one. @Aman-Codes  , I actually removed the Code of Conduct (was following the same format) when laying down the initial format. But I think a code of conduct is more relevant when we have more contributors out in the wild and brewing community. Also the guidelines etc stuff must also be discussed. @anoopsingh1996  @sagar-sehgal  @MahamArif  need you advice on this one.

**Comment by rajatkb** [comment]
@Aman-Codes  you can make a PR for same.

**Comment by Aman-Codes** [comment]
@rajatkb Sure sir please can you share your email Id where participant can report any unacceptable behavior.

**Comment by rajatkb** [comment]
> 
> 
> @rajatkb Sure sir please can you share your email Id where participant can report any unacceptable behavior.

rajatk.dev@gmail.com
