### ISSUE TITLE
Guide 2 Research Scraper needs a redirect method  to get pages

### ISSUE THREAD

**Issue by manasakalaga** [rajatkb/Conference-Notify#68]
**Is your feature request related to a problem? Please describe.**
Due to the way Guide2Research works, `self.get_page` method in the `Scrapper` base class cannot be used. There has been a discussion about this in #43   

**Describe the solution you'd like**
An additional method/modification to the current `get_page` method to allow for redirects

**Describe alternatives you've considered**
There's no alternative way that this problem could be handled.

**Comment by rajatkb** [comment]
@manasakalaga  put the respective PR for it.
