### ISSUE TITLE
[Docs] update Scrapper-Service Readme.md with Datamodel Schema used.

### ISSUE THREAD

**Issue by rajatkb** [rajatkb/Conference-Notify#7]
The data model schemas are missing from the readme. This needs to be included in order to help others work with their mongo instances and query the data.

**REQUIREMENTS**
1. Readme doc inside the Scrapper-Service , not the root one should contain a schema of the mongodb data

2. make any necessary update to the readme that will help people understand about what is indexed, and how the insertion in happening for multiple scrappers.

**Comment by vipuldcoder** [comment]
I am interested with the issue.

**Comment by rajatkb** [comment]
@vipuldcoder  I require and update on this ASAP.

**Comment by vipuldcoder** [comment]
I am working on it.

**Comment by rajatkb** [comment]
@vipuldcoder  I am assigning a deadline of **19 March** on the issue please revert back ASAP and resolve it.

**Comment by vipul-aggarwal-099** [comment]
I need the deadline to 1st April.
