### ISSUE TITLE
[Bug] add close method to database and a process exit event handler for calling it.

### ISSUE THREAD

**Issue by rajatkb** [rajatkb/Conference-Notify#72]
**Describe the bug**
Currently the database connection is sustained even after the process is killed. With language like python we get destructors which can close the connection when interpreter is closed. But with Node.js we need to tap into the process exit event and close the connection.

Why closing is necessary. Because leaving connection is never safe, It creates unpredictable behaviour from both application and the database server-side.

**Expected behavior**
All connection should be closed down when the application receives a kill signal.

**Comment by vipul-aggarwal-099** [comment]
I am interested with this issue.
