### ISSUE TITLE
[Bug] Scrapper service when run on windows machine stop after running few hours

### ISSUE THREAD

**Issue by rajatkb** [rajatkb/Conference-Notify#8]
The service is written in Python so that should be taken in consideration. 
* The process after a few hours of execution stop printing logs. Although by that time a huge amount of data is collected at MongoDB so updates are frequent. 
* So without logs and any new insertion update from MongoDB it's difficult to detect what is going wrong. 
* The process, however, does not crashes evident from task manager.
* No resource crunch. It's 16GB  RAM machine with i7 4770.  The CPU utilization is at minimal and so as to ram.

Would post a screenshot once this happens again

**Comment by vipuldcoder** [comment]
I am interested with the issue.

**Comment by rajatkb** [comment]
The issue was resolved last night by me. Closing it. It was a network bug in one of my code for `requests.get()` not worth investing time from the rest of team.

**Comment by rajatkb** [comment]
**Resolution**
* add timeout parameter in `requests.get()`
* The default makes it wait idefinitely i.e when network drops the connection never times out.
