### ISSUE TITLE
Edit getOne() method to fetch the particular conference Detail

### ISSUE THREAD

**Issue by Kajol-Kumari** [rajatkb/Conference-Notify#88]
**Describe the bug**
Currently getOne() function is fetching the dummy testing conference.

**To Reproduce**
write a test file and call getOne() method

**Expected behavior**
getOne() method should have returned a particular conference based on its `id` or any other `PK`

where to look?
Notifier-service/src/services/conference.ts

**Comment by amandhamija98** [comment]
Hi may I be assigned

**Comment by amandhamija98** [comment]
Hi, I had a doubt, according to what I understood, I have to write a test case for getOne method right?
