### ISSUE TITLE
Fix broken links in Readme.md

### ISSUE THREAD

**Issue by Aman-Codes** [rajatkb/Conference-Notify#94]
**Describe the bug**
@rajatkb @anoopsingh1996 @sagar-sehgal The link to contributing.md and license in readme.md is not working properly. As a GSSOC participant I would like to fix it.

**Comment by rajatkb** [comment]
Ya sure put a PR for it. Also do put a screenshot of the defective and fixed behaviour.

**Comment by Aman-Codes** [comment]
@rajatkb @anoopsingh1996 @sagar-sehgal Opened the pull request. Kindly review it.
